### PR TITLE
Add Adafruit feather and itsybitsy rp2040

### PR DESCRIPTION
**Pull request by hathach**
Draft PR for discussion only, should be toward rpi/board-headers later on.

This takes discussion from https://github.com/raspberrypi/pico-sdk/pull/138 into account. Though the board definition doesn't do much than define UART, LED pin along with Flash size for Feather & ItsyBitsy RP2040. Currently there is no `PICO_DEFAULT_` for I2C or SPI, but it still be a good start to have user to blink from pico-sdk on our actual hardware (still need https://github.com/raspberrypi/pico-examples/pull/57) 

from RPi document to build with our board

```
cd pico-examples
mkdir build-feather
cd build-feather
cmake -D"PICO_BOARD=adafruit_feather_rp2040" ..
```

Then proceed to build normally with generated make.

### CODE REVIEW

**Comment by ZodiusInfuser** [comment]
Hi. A suggestion for you board configs, include a define near the bottom of your files that can be used by code to check what board is being used. For instance the `vgaboard.h` that is already in the SDK has `#define PICO_VGA_BOARD` on the third line from the bottom:
https://github.com/raspberrypi/pico-sdk/blob/2d5789eca89658a7f0a01e2d6010c0f254605d72/src/boards/include/boards/vgaboard.h#L102

For our Pimoroni boards we've added `#define PIMORONI_TINY2040` and `#define PIMORONI_KEYBOW2040`

**Comment by hathach** [comment]
Ah thanks for the tip, it is indeed very handy, I basically mirror the `pico.h` which doesn't define that. It seems to be quite important, maybe, I should put it in the beginning instead :smiley:

**Comment by hathach** [comment]
add `PICO_DEFAULT_WS2812_PIN` following https://github.com/raspberrypi/pico-sdk/issues/188

**Review by ladyada — APPROVED** [review]

**Comment by hathach** [comment]
closed, official PR is submitted to https://github.com/raspberrypi/pico-sdk/pull/194

**Pull request closed without merging**
